version: "3"

networks:
  api:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./src:/src
    ports:
      - "8001:8000"
    image: app:django
    container_name: ${APP_NAME}
    env_file:
      - .env
    command: python /src/manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    networks:
        - api

  postgres:
    image: postgres:16.4-alpine
    container_name: ${DB_HOST}_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}

      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: "trust"

    networks:
        - api