EMPTY_STRING = ''
ID = 'id'
CSV = 'csv'
DATA = 'data'
HASH = 'hash'
NAME = 'name'
DATE = 'date'
TYPE = 'type'
AMOUNT = 'amount'
SOURCE = 'source'
TARGET = 'target'
REQUEST = 'request'
MESSAGE = 'message'
REQUIRED = 'required'
DIFFERENCE = 'difference'
SOURCE_FILE = 'source_file'
SOURCE_HASH = 'source_hash'
TARGET_FILE = 'target_file'
TARGET_HASH = 'target_hash'
COMBINED_HASH = 'combined_hash'
DISCREPANCIES = 'discrepancies'
MISSING_IN_TARGET = 'missing_in_target'
MISSING_IN_SOURCE = 'missing_in_source'
FILE_UPLOADED_SUCCESSFULLY = 'Files uploaded successfully.'
FILE_RECONCILIATION_EXIST = 'You have already performed reconciliation for these files.'


